lib/tombo_chat_web/router.ex
defmodule TomboChatWeb.Router do
  use TomboChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TomboChatWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomboChatWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/admin", AdminSettingController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/rooms", RoomController
    resources "/account_activation", AccountActivationController, only: [:edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TomboChatWeb do
  #   pipe_through :api
  # end

  if Mix.env() == :dev do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard("/dashboard")
    end

    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/tombo_chat_web/controllers/session_controller.ex
defmodule TomboChatWeb.SessionController do
  use TomboChatWeb, :controller
  plug :authenticate_user when action in [:delete]

  def new(conn, _) do
    conn
    |> render("new.html")
  end

  def create(
        conn,
        %{"session" => %{"username" => username, "password" => pass}}
      ) do
    case TomboChat.Accounts.authenticate_by_username_and_pass(username, pass) do
      {:ok, user} ->
        conn
        |> TomboChatWeb.Auth.login(user)
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, _reason} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> TomboChatWeb.Auth.logout()
    |> redirect(to: Routes.page_path(conn, :index))
  end
end

lib/tombo_chat_web/views/session_view.ex
defmodule TomboChatWeb.SessionView do
  use TomboChatWeb, :view
end

lib/tombo_chat_web/templates/session/new.html.eex
<div class="columns is-centered">
  <div class="column is-one-quarter">
  <p class="title">Log in</p>
    <!-- Plug.conn structs are useful
         when you're creating forms that aren't backed by a changeset -->
    <%= form_for @conn, Routes.session_path(@conn, :create), [as: :session], fn f -> %>
      <div class="field">
        <div class="control">
        <%= text_input f, :username, placeholder: "Username", class: "input" %>
        <%= error_tag f, :username %>
        </div>
      </div>
      <div class="field">
        <div class="control">
        <%= password_input f, :password, placeholder: "Password", class: "input" %>
        <%= error_tag f, :password %>
        </div>
      </div>
      <%= submit "Log in", class: "button is-success" %>
    <% end %>
  </div>
</div>