lib/tombo_chat_web/router.ex
defmodule TomboChatWeb.Router do
  use TomboChatWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug TomboChatWeb.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TomboChatWeb do
    pipe_through :browser

    get "/", PageController, :index
    get "/admin", AdminSettingController, :index

    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/rooms", RoomController
    resources "/account_activation", AccountActivationController, only: [:edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", TomboChatWeb do
  #   pipe_through :api
  # end

  if Mix.env() == :dev do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard("/dashboard")
    end

    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/tombo_chat_web/views/layout_view.ex
defmodule TomboChatWeb.LayoutView do
  use TomboChatWeb, :view
end

lib/tombo_chat_web/templates/layout/admin_setting.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Tombo Chat</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header></header>
    <main role="main">
      <%= render(@view_module, @view_template, assigns) %>
      <br/>
      <%= case get_flash(@conn) do %>
        <% %{"info" => message} -> %>
          <article class="message is-info">
            <div class="message-body" role="alert"><%= message %></div>
          </article>
        <% %{"error" => message} -> %>
          <article class="message is-danger">
            <div class="message-body" role="alert"><%= message %></div>
          </article>
        <% _ -> %><%= nil %>
      <% end %>
    </main>
    <footer></footer>
  </body>
</html>

lib/tombo_chat_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Tombo Chat</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body>
    <header>
      <section class="hero is-info">
      <div class="hero-body">
        <div class="columns">
          <div class="column is-10">
            <h1 class="title">
              <%= link "🍺OkazaKirin.beam🍺", to: Routes.page_path(@conn, :index) %>
            </h1>
          </div>
          <div class="column is-2">
          <nav role="navigation">
                    <!-- TomboChatWeb stored the user under conn.assigns.current_user -->
                      <%= if @current_user do %>
                        <strong><%= link @current_user.name, to: Routes.user_path(@conn, :show, @current_user) %></strong> /
                        <%= link "Log out",
                                to: Routes.session_path(@conn, :delete, @current_user),
                                method: "delete" %>
                      <% else %>
                          <%= link "Register", to: Routes.user_path(@conn, :new) %> /
                          <%= link "Log in", to: Routes.session_path(@conn, :new) %>
                      <% end %>
                  </nav>
           </div>
        </div>
      </div>
      </section>
    </header>
    <main role="main">
      <%= render(@view_module, @view_template, assigns) %>
      <br/>
      <%= case get_flash(@conn) do %>
        <% %{"info" => message} -> %>
          <article class="message is-info">
            <div class="message-body" role="alert"><%= message %></div>
          </article>
        <% %{"error" => message} -> %>
          <article class="message is-danger">
            <div class="message-body" role="alert"><%= message %></div>
          </article>
        <% _ -> %><%= nil %>
      <% end %>
    </main>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/tombo_chat_web/templates/layout/email.html.eex
<html>
  <head>
    <link rel="stylesheet" href="<%#= static_url(TomboChatWeb.Endpoint, "/css/email.css") %>">
  </head>
  <body>
    <%= render @view_module, @view_template, assigns %>
  </body>
</html>

lib/tombo_chat_web/templates/layout/email.text.eex
<%= render @view_module, @view_template, assigns %>